//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo005_Mangas_ApiRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mangaEntities : DbContext
    {
        public mangaEntities()
            : base("name=mangaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_AUTOR> TBL_AUTOR { get; set; }
        public virtual DbSet<TBL_CAPITULO> TBL_CAPITULO { get; set; }
        public virtual DbSet<TBL_EDITORIAL> TBL_EDITORIAL { get; set; }
        public virtual DbSet<TBL_MANGA> TBL_MANGA { get; set; }
    }
}
