//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo005_Mangas_ApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CAPITULO
    {
        public int id_capitulo { get; set; }
        public Nullable<int> id_manga { get; set; }
        public string titulo_capitulo { get; set; }
        public Nullable<int> numero_capitulo { get; set; }
    
        public virtual TBL_MANGA TBL_MANGA { get; set; }
    }
}
