//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo005_Mangas_ApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AUTOR
    {
    
        public int id_autor { get; set; }
        public string nombre_autor { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_autor { get; set; }
    
    }
}
