//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo005_Mangas_ApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MANGA
    {
    
        public int id_manga { get; set; }
        public string nombre_espaniol_manga { get; set; }
        public Nullable<int> id_autor { get; set; }
        public Nullable<int> id_editorial { get; set; }
        public string logo_manga { get; set; }
    
    }
}
